const {DataTypes} = require("sequelize");
module.exports = (sequelize)=>{
    sequelize.define("CabVentas",{
        id:{
            type:DataTypes.BIGINT,
            autoIncrement:true,
            primaryKey:true,
        },
        fecha:{
            type:DataTypes.DATEONLY,
            defaultValue:DataTypes.NOW,
        },
        serieDcmto:{
            type:DataTypes.STRING,
            allowNull: false,
        },
        correlativoDcmto:{
            type:DataTypes.STRING,
            allowNull: false,
        },
        idContacto:{
            type:DataTypes.BIGINT,
        },
        idDirOrigen:{
            type:DataTypes.BIGINT,
        },
        idDirEntrega:{
            type:DataTypes.BIGINT,
        },
        observaciones:{
            type:DataTypes.STRING,
        },
        idDocAlmacen:{
            type:DataTypes.BIGINT,
        },
        idVendedor:{
            type:DataTypes.INTEGER,
        },
        idTecnico:{
            type:DataTypes.INTEGER,
        },
        numPlacas:{
            type:DataTypes.STRING,
        },
        tipoCambio:{
            type:DataTypes.DECIMAL(12,2),
        },
        porcentajeIGV:{
            type:DataTypes.DECIMAL(12,2),
        },
        emailDestino:{
            type:DataTypes.STRING,
        },
        rutaDcmtoPDF:{
            type:DataTypes.STRING,
        },
        exonerado:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        moneda:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        factElectOK:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        anticipo:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idHistorico:{
            type:DataTypes.BIGINT,
        },
    },
    {
        timestamps:false,
        tableName: "CabVentas"
    }
    )
}