const {DataTypes} = require("sequelize");

module.exports = (sequelize)=>{
    sequelize.define("DetVentas",{
        id:{
            type:DataTypes.BIGINT,
            autoIncrement:true,
            primaryKey:true,
        },
        cantidad:{
            type:DataTypes.DECIMAL(12,2),
            allowNull: false,
        },
        vvUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        vvUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        porcentajeDescUnit:{
            type:DataTypes.DECIMAL(12,2),
        },
        descUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        descUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        vvNetoUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        vvNetoUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        vvNetoTotMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        vvNetoTotME:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvTotalMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvTotalME:{
            type:DataTypes.DECIMAL(12,2),
        },
        pvUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        pvUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        pvTotalMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        pvTotalME:{
            type:DataTypes.DECIMAL(12,2),
        },
        rutaFotoInstalacion01:{
            type:DataTypes.STRING,
        },
        rutaFotoInstalacion02:{
            type:DataTypes.STRING,
        },
        exonerado:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idApruebaDesc:{
            type:DataTypes.INTEGER,
        },
        fechaApruebaDesc:{
            type:DataTypes.DATE,
        },
        descUnitMontoMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        descUnitMontoME:{
            type:DataTypes.DECIMAL(12,2),
        },
        nroMesesGarantia:{
            type:DataTypes.INTEGER,
        },
        idPreciosCliProv:{
            type:DataTypes.BIGINT,
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idHistorico:{
            type:DataTypes.BIGINT,
        },
    },
    {
        timestamps:false,
        tableName: "DetVentas"
    }
    )
}