const {DataTypes} = require("sequelize");
module.exports = (sequelize)=>{
    sequelize.define("TipoCambio",{
        id:{
            type:DataTypes.INTEGER,
            autoIncrement:true,
            primaryKey:true,
        },
        fecha:{
            type:DataTypes.DATEONLY,
            defaultValue:DataTypes.NOW,
            unique:true,
        },
        compra:{
            type:DataTypes.DECIMAL(12,3),
            allowNull:false,
        },
        venta:{
            type:DataTypes.DECIMAL(12,3),
            allowNull:false,
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idHistorico:{
            type:DataTypes.INTEGER,
        },
    },
    {
        timestamps:false,
        tableName: "TipoCambio"
    }
    )
}
