const {DataTypes} = require("sequelize");
module.exports = (sequelize)=>{
    sequelize.define("TipoDocumento",{
        id:{
            type:DataTypes.INTEGER,
            autoIncrement:true,
            primaryKey:true,
        },
        descripcion:{
            type:DataTypes.STRING,
            allowNull: false,
        },
        iniciales:{
            type:DataTypes.STRING,
        },
        codSunat:{
            type:DataTypes.STRING,
        },
        operacionesCompra:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        operacionesAlmacen:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        operacionesVenta:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        facturacionElectronica:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idHistorico:{
            type:DataTypes.INTEGER,
        },
    },
    {
        timestamps:false,
        tableName: "TipoDocumento"
    }
    )
}
