const {DataTypes} = require("sequelize");

module.exports = (sequelize)=>{
    sequelize.define("DetCompras",{
        id:{
            type:DataTypes.BIGINT,
            autoIncrement:true,
            primaryKey:true,
        },
        cantidad:{
            type:DataTypes.DECIMAL(12,2),
            allowNull: false,
        },
        vcUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        vcUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        porcentajeDescUnit:{
            type:DataTypes.DECIMAL(12,2),
        },
        descUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        descUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        vcNetoUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        vcNetoUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        vcNetoTotMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        vcNetoTotME:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvTotalMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        igvTotalME:{
            type:DataTypes.DECIMAL(12,2),
        },
        pcUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        pcUnitME:{
            type:DataTypes.DECIMAL(12,2),
        },
        pcTotalMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        pcTotalME:{
            type:DataTypes.DECIMAL(12,2),
        },
        exonerado:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        descUnitMontoMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        descUnitMontoME:{
            type:DataTypes.DECIMAL(12,2),
        },
        nroMesesGarantia:{
            type:DataTypes.INTEGER,
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idHistorico:{
            type:DataTypes.BIGINT,
        },
    },
    {
        timestamps:false,
        tableName: "DetCompras"
    }
    )
}