const {DataTypes} = require("sequelize");
module.exports = (sequelize)=>{
    sequelize.define("Acceso",{
        id:{
            type:DataTypes.INTEGER,
            primaryKey:true,
        },
        descripcion:{
            type:DataTypes.STRING,
            allowNull: false,
        },
        lectura:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        escritura:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        creacion:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        eliminacion:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        reportes:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:true
        },
        cesado:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
    },
    {timestamps:false}
    )
}