const {DataTypes} = require("sequelize");
module.exports = (sequelize)=>{
    sequelize.define("Personal",{
        id:{
            type:DataTypes.INTEGER,
            autoIncrement:true,
            primaryKey:true,
        },
        nombres:{
            type:DataTypes.STRING,
            allowNull: false,
        },
        email:{
            type:DataTypes.STRING,
        },
        telefonos:{
            type:DataTypes.STRING,
        },
        urlFoto:{
            type:DataTypes.STRING,
        },
        nroDocIdentidad:{
            type:DataTypes.STRING,
        },
        vendedor:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        cesado:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idHistorico:{
            type:DataTypes.INTEGER,
        },
    },
    {
        timestamps:false,
        tableName: "Personal"
    }
    )
}
