const {DataTypes} = require("sequelize");
module.exports = (sequelize)=>{
    sequelize.define("CabMovAlmacen",{
        id:{
            type:DataTypes.BIGINT,
            autoIncrement:true,
            primaryKey:true,
        },
        fecha:{
            type:DataTypes.DATEONLY,
            defaultValue:DataTypes.NOW,
        },
        serieDcmto:{
            type:DataTypes.STRING,
            allowNull: false,
        },
        correlativoDcmto:{
            type:DataTypes.STRING,
            allowNull: false,
        },
        idContacto:{
            type:DataTypes.BIGINT,
        },
        idDirOrigen:{
            type:DataTypes.BIGINT,
        },
        idDirEntrega:{
            type:DataTypes.BIGINT,
        },
        idTransportista:{
            type:DataTypes.BIGINT,
        },
        idChofer:{
            type:DataTypes.BIGINT,
        },
        observaciones:{
            type:DataTypes.STRING,
        },
        idDocOrigenVenta:{
            type:DataTypes.BIGINT,
        },
        idDocOrigenCompra:{
            type:DataTypes.BIGINT,
        },
        tipoCambio:{
            type:DataTypes.DECIMAL(12,2),
        },
        emailDestino:{
            type:DataTypes.STRING,
        },
        numGuiaSunat:{
            type:DataTypes.STRING,
        },
        fechaGuiaSunat:{
            type:DataTypes.DATEONLY,
            defaultValue:DataTypes.NOW,
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        idHistorico:{
            type:DataTypes.BIGINT,
        },
    },
    {
        timestamps:false,
        tableName: "CabMovAlmacen"
    }
    )
}