const {DataTypes} = require("sequelize");
module.exports = (sequelize)=>{
    sequelize.define("DetMovAlmacen",{
        id:{
            type:DataTypes.BIGINT,
            primaryKey:true,
        },
        fecha:{
            type:DataTypes.DATEONLY,
            defaultValue:DataTypes.NOW,
        },
        nroLote:{
            type:DataTypes.STRING,
        },
        nroEnvase:{
            type:DataTypes.STRING,
        },
        nroSerie:{
            type:DataTypes.STRING,
        },
        fechaProduccion:{
            type:DataTypes.DATEONLY,
        },
        fechaVencimiento:{
            type:DataTypes.DATEONLY,
        },
        cantidad:{
            type:DataTypes.DECIMAL(12,2),
            allowNull: false,
        },
        pesoKG:{
            type:DataTypes.DECIMAL(12,2),
            allowNull: false,
        },
        valorUnitMN:{
            type:DataTypes.DECIMAL(12,2),
        },
        codUbicacionOrigen:{
            type:DataTypes.BIGINT,
        },
        codUbicacionDestino:{
            type:DataTypes.BIGINT,
        },
        idDetCompra:{
            type:DataTypes.BIGINT,
        },
        idDetVenta:{
            type:DataTypes.BIGINT,
        },
        created:{
            type:DataTypes.BOOLEAN,
            defaultValue:true
        },
        cesado:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        borradoLogico:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
    },
    {timestamps:false}
    )
}