const {DataTypes} = require("sequelize");

module.exports = (sequelize)=>{
    sequelize.define("KardexAlmacen",{
        id:{
            type:DataTypes.BIGINT,
            autoIncrement:true,
            primaryKey:true,
        },
        fecha:{
            type:DataTypes.DATEONLY,
            defaultValue:DataTypes.NOW,
        },
        ingEgr:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        },
        saldoIniCant:{
            type:DataTypes.DECIMAL(12,2),
        },
        ingCUnit:{
            type:DataTypes.DECIMAL(12,2),
        },
        cantidad:{
            type:DataTypes.DECIMAL(12,2),
        },
        saldoIniCUnit:{
            type:DataTypes.DECIMAL(12,2),
        },
        saldoIniCTot:{
            type:DataTypes.DECIMAL(12,2),
        },
        saldoFinCant:{
            type:DataTypes.DECIMAL(12,2),
        },
        saldoFinCUnit:{
            type:DataTypes.DECIMAL(12,2),
        },
        saldoFinCTot:{
            type:DataTypes.DECIMAL(12,2),
        },
        idAlmacen:{
            type:DataTypes.INTEGER,
        },
        idCabMovAlmacen:{
            type:DataTypes.BIGINT,
        },
        idDetMovAlmacen:{
            type:DataTypes.BIGINT,
        },
        nroEnvase:{
            type:DataTypes.STRING,
        },
        nroLote:{
            type:DataTypes.STRING,
        },
        nroSerie:{
            type:DataTypes.STRING,
        },
        fechaProduccion:{
            type:DataTypes.DATEONLY,
        },
        fechaVencimiento:{
            type:DataTypes.DATEONLY,
        },
    },
    {
        timestamps:false,
        tableName: "KardexAlmacen"
    }
    )
}